# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'C:\Users\Natsu\PycharmProjects\MPHMiner\gui\miner_gui.ui'
#
# Created by: PyQt5 UI code generator 5.10
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_Form(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(640, 480)
        self.verticalLayout = QtWidgets.QVBoxLayout(Form)
        self.verticalLayout.setObjectName("verticalLayout")
        self.horizontalLayout_4 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_4.setSizeConstraint(QtWidgets.QLayout.SetDefaultConstraint)
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        self.btnConfig = QtWidgets.QPushButton(Form)
        self.btnConfig.setText("")
        self.btnConfig.setFlat(True)
        self.btnConfig.setObjectName("btnConfig")
        self.horizontalLayout_4.addWidget(self.btnConfig)
        spacerItem = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_4.addItem(spacerItem)
        self.btnMinimize = QtWidgets.QPushButton(Form)
        self.btnMinimize.setText("")
        self.btnMinimize.setFlat(True)
        self.btnMinimize.setObjectName("btnMinimize")
        self.horizontalLayout_4.addWidget(self.btnMinimize)
        self.btnRestore = QtWidgets.QPushButton(Form)
        self.btnRestore.setText("")
        self.btnRestore.setFlat(True)
        self.btnRestore.setObjectName("btnRestore")
        self.horizontalLayout_4.addWidget(self.btnRestore)
        self.btnClose = QtWidgets.QPushButton(Form)
        self.btnClose.setText("")
        self.btnClose.setFlat(True)
        self.btnClose.setObjectName("btnClose")
        self.horizontalLayout_4.addWidget(self.btnClose)
        self.verticalLayout.addLayout(self.horizontalLayout_4)
        spacerItem1 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout.addItem(spacerItem1)
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.lblTest1 = QtWidgets.QLabel(Form)
        self.lblTest1.setAlignment(QtCore.Qt.AlignCenter)
        self.lblTest1.setObjectName("lblTest1")
        self.horizontalLayout_3.addWidget(self.lblTest1)
        self.lblTest2 = QtWidgets.QLabel(Form)
        self.lblTest2.setAlignment(QtCore.Qt.AlignCenter)
        self.lblTest2.setObjectName("lblTest2")
        self.horizontalLayout_3.addWidget(self.lblTest2)
        self.lblTest3 = QtWidgets.QLabel(Form)
        self.lblTest3.setAlignment(QtCore.Qt.AlignCenter)
        self.lblTest3.setObjectName("lblTest3")
        self.horizontalLayout_3.addWidget(self.lblTest3)
        self.verticalLayout.addLayout(self.horizontalLayout_3)
        spacerItem2 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout.addItem(spacerItem2)
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.lblCoinName = QtWidgets.QLabel(Form)
        self.lblCoinName.setAlignment(QtCore.Qt.AlignCenter)
        self.lblCoinName.setObjectName("lblCoinName")
        self.horizontalLayout_2.addWidget(self.lblCoinName)
        self.lblCoinAlgo = QtWidgets.QLabel(Form)
        self.lblCoinAlgo.setAlignment(QtCore.Qt.AlignCenter)
        self.lblCoinAlgo.setObjectName("lblCoinAlgo")
        self.horizontalLayout_2.addWidget(self.lblCoinAlgo)
        self.lblHashrate = QtWidgets.QLabel(Form)
        self.lblHashrate.setAlignment(QtCore.Qt.AlignCenter)
        self.lblHashrate.setObjectName("lblHashrate")
        self.horizontalLayout_2.addWidget(self.lblHashrate)
        self.verticalLayout.addLayout(self.horizontalLayout_2)
        spacerItem3 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout.addItem(spacerItem3)
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.btnStart = QtWidgets.QPushButton(Form)
        self.btnStart.setObjectName("btnStart")
        self.horizontalLayout.addWidget(self.btnStart)
        self.btnStop = QtWidgets.QPushButton(Form)
        self.btnStop.setObjectName("btnStop")
        self.horizontalLayout.addWidget(self.btnStop)
        self.verticalLayout.addLayout(self.horizontalLayout)

        self.retranslateUi(Form)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "Form"))
        self.lblTest1.setText(_translate("Form", "Total Balance"))
        self.lblTest2.setText(_translate("Form", "Misc"))
        self.lblTest3.setText(_translate("Form", "Coin Balance"))
        self.lblCoinName.setText(_translate("Form", "Coin"))
        self.lblCoinAlgo.setText(_translate("Form", "Algo"))
        self.lblHashrate.setText(_translate("Form", "Hash"))
        self.btnStart.setText(_translate("Form", "Start"))
        self.btnStop.setText(_translate("Form", "Stop"))

